# Generated by Django 4.1.6 on 2023-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupload',
            name='imagefile',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
